#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

include Hookit::Helper::NFS

converged_config = converge( Hooky::Parity::CONFIG_DEFAULTS, payload[:config] || {} )

basepath = clean_writables([converged_config[:basepath]])[0]

execute "send data to backup container" do
  command "tar cz --exclude='./#{basepath}/chains' -C /data/var/db/unfs . | ssh -o StrictHostKeyChecking=no #{payload[:warehouse][:host]} 'cat > /data/var/db/unfs/#{payload[:warehouse][:backup_id]}.tgz'"
  cwd "/data/var/db/unfs"
end
