#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# This hook will export the data to the new members while the service is
# still online.
execute "send bulk data to new member" do
  command "tar -cf - /data/var/db/parity | ssh -o StrictHostKeyChecking=no #{payload[:member][:local_ip]} tar -C / -xpf -"
end