#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

include Hookit::Helper::NFS

converged_config = converge( Hooky::Parity::CONFIG_DEFAULTS, payload[:config] || {} )

# find available space
new_member_stat = `ssh -o StrictHostKeyChecking=no #{payload[:member][:local_ip]} stat -f --format=\\\"%a %S\\\" /data/var/db/unfs`
available_space = new_member_stat.split(' ')[0].to_i * new_member_stat.split(' ')[1].to_i

# find needed space
needed_space = `du -bs /data/var/db/unfs`.split(' ')[0].to_i

if available_space < needed_space
  puts "Receiving side too small!!"
  exit 1
end

basepath = clean_writables([converged_config[:basepath]])[0]

execute "send bulk data to new member" do
  command "tar czf - --exclude='./#{basepath}/chains' -C /data/var/db/unfs . | ssh #{payload[:member][:local_ip]} tar xzf - -C /data/var/db/unfs/"
  cwd "/data/var/db/unfs"
end