#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# Ensure the parity is stopped before running import/export
service 'parity' do
  action :disable
  init :runit
  only_if {`sv status parity` =~ /^run/}
  not_if { !Dir.exist?('/etc/service/parity') }
end

directory '/etc/service/parity' do
  action :delete
  not_if { !Dir.exist?('/etc/service/parity') }
end

# Start ssh daemon so that rsync over ssh can be used
directory '/etc/service/ssh' do
  recursive true
end

directory '/etc/service/ssh/log' do
  recursive true
end

template '/etc/service/ssh/log/run' do
  mode 0755
  source 'log-run.erb'
  variables ({ svc: "ssh" })
end

template '/etc/service/ssh/run' do
  mode 0755
  source 'run-root.erb'
  variables ({ exec: "/opt/gonano/sbin/sshd -D -e" })
end

sleep 5

service 'ssh' do
  action :enable
  init :runit
end

ensure_socket 'ssh' do
  port '22'
  action :listening
end