#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'
require 'json'

plan = {
  redundant: false,
  horizontal: false,
  users: [],
  ips: [:default],
  port: 30303,
  port_ui: 8180,
  port_rpc: 8545,
  port_ws: 8546,
  behaviors: []
}

puts JSON.pretty_generate(plan)